version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: npx webpack watch
  web:
    image: nginx:alpine
    ports:
      - 8888:80
    privileged: true
    volumes:
      - ./public/:/usr/share/nginx/html
